### ISSUE TITLE
Add tags and category support

### ISSUE THREAD

**Issue by peng1999** [Keats/hyde#7]
Maybe just port templates from other theme like [feather](https://github.com/piedoom/feather) is enough?

**Comment by Keats** [comment]
This is a port of an existing theme which doesn't use taxonomies so adding doesn't make sense. You can add them yourself pretty easily if wanted.
Do keep in mind that the next version of Gutenberg (https://github.com/Keats/gutenberg/pull/290) will completely revamp how taxonomies are handled
